#version: "3.8"
#services:
#  postgres:
#    image: postgres:15 # Flyway OSS supports up to PG‑15; 16 needs extra plugin
#    restart: always
#    ports:
#      - "5432:5432"          # host → container
#    volumes:
#      - pgdata_auth:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: authdb
#      POSTGRES_USER: auth
#      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-!Aa123456}"
#
#  auth-service:
#    image: auth-service:latest                 # or image: your‑repo/auth-service:1.0
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
#      SPRING_DATASOURCE_USERNAME: auth
#      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD:-!Aa123456}"
#      SPRING_PROFILES_ACTIVE: docker
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"          # expose API to host
#
#volumes:
#  pgdata_auth: