$schema: "https://github.com/hyperledger-labs/fablo/releases/download/2.2.0/schema.json"
global:
  fabricVersion: "2.4.2"
  # RAFT requires TLS
  tls: true
  peerDevMode: false
  monitoring:
    loglevel: "debug"

orgs:
  - organization:
      name: Org1
      domain: org1.example.com
    peer:
      instances: 2      # two peers: peer0, peer1
      db: LevelDb
    orderers:
      - groupName: orderer-group
        type: raft
        instances: 1

channels:
  - name: voting-channel
    orgs:
      - name: Org1
        peers:
          - peer0
          - peer1

chaincodes:
  - name: voting-contract
    version: "1.0"
    lang: node
    channel: voting-channel
    directory: ./chaincode/voting-contract
    initRequired: false
