package com.audit;

public class AuditFormats {
	
	public static enum Acces {
		GRANTED, UNNOUTORIZED
	}
	
	public static enum Entity {
		DEVICE, PROFILE, DEVICE_TYPE, ROUTER, DEVICE_USER, NOTIFICATION, DEVICE_CMD, SMS_RECEIVER, SMS_SEND, USER, AUDIT
	}
	
	public static enum Event {
		CREATE, UPDATE, DELETE, DELETE_USER_DEVICE, SEND, ASSIGN_USER_DEVICE, REMOVE_ASSIGNMENT, LIST, LIST_ONE, LIST_BY, UPDATE_PASS, RESET, SMS_INSERT, DELETE_ROUTER_USER, ASSIGN_ROUTER_USER, ASSIGN_ROUTER_MASTER
	}
}
